import asyncio
from motor.motor_asyncio import AsyncIOMotorClient

MONGO_URL = "mongodb://localhost:27017"
DB_NAME = "mimetic_ai"

symptoms = [
    {"name": "fiebre", "description": "Temperatura corporal elevada (>38°C)", "category": "generales"},
    {"name": "tos", "description": "Tos seca o productiva", "category": "respiratorio"},
    {"name": "dolor de cabeza", "description": "Cefalea o dolor craneal", "category": "neurologico"},
    {"name": "fatiga", "description": "Cansancio o debilidad general", "category": "generales"},
    {"name": "dificultad para respirar", "description": "Disnea o falta de aire", "category": "respiratorio"},
    {"name": "dolor de garganta", "description": "Odinofagia o dolor faríngeo", "category": "respiratorio"},
    {"name": "congestión nasal", "description": "Nariz tapada o mucosidad", "category": "respiratorio"},
    {"name": "escalofríos", "description": "Sensación de frío con temblores", "category": "generales"},
    {"name": "dolor muscular", "description": "Mialgias o dolores corporales", "category": "musculoesqueletico"},
    {"name": "pérdida del gusto", "description": "Ageusia o pérdida del sentido del gusto", "category": "neurologico"},
    {"name": "pérdida del olfato", "description": "Anosmia o pérdida del olfato", "category": "neurologico"},
    {"name": "náuseas", "description": "Náuseas o ganas de vomitar", "category": "digestivo"},
    {"name": "vómito", "description": "Vómito o emesis", "category": "digestivo"},
    {"name": "diarrea", "description": "Heces sueltas o líquidas frecuentes", "category": "digestivo"},
    {"name": "dolor abdominal", "description": "Dolor en la región del abdomen", "category": "digestivo"},
    {"name": "deshidratación", "description": "Pérdida excesiva de líquidos corporales", "category": "generales"},
    {"name": "sarpullido", "description": "Erupción cutánea o rash", "category": "dermatologico"},
    {"name": "dolor en el pecho", "description": "Dolor torácico", "category": "cardiovascular"},
    {"name": "presión arterial alta", "description": "Hipertensión o PA elevada", "category": "cardiovascular"},
    {"name": "mareos", "description": "Vértigo o sensación de desmayo", "category": "neurologico"},
    {"name": "dolor de oído", "description": "Otalgia o dolor auricular", "category": "otologico"},
    {"name": "secreción del oído", "description": "Otorrea o líquido del oído", "category": "otologico"},
    {"name": "ardor al orinar", "description": "Disuria o dolor miccional", "category": "urinario"},
    {"name": "frecuencia urinaria", "description": "Polaquiuria u orinar con frecuencia", "category": "urinario"},
    {"name": "dolor lumbar", "description": "Dolor en la región baja de la espalda", "category": "musculoesqueletico"},
    {"name": "fiebre alta persistente", "description": "Fiebre >39°C que no cede", "category": "generales"},
    {"name": "confusión", "description": "Estado de confusión o desorientación", "category": "neurologico"},
    {"name": "rigidez de cuello", "description": "Rigidez nucal o cuello tieso", "category": "neurologico"},
    {"name": "dolor articular", "description": "Artralgia o dolor en las articulaciones", "category": "musculoesqueletico"},
    {"name": "hinchazón", "description": "Edema o inflamación de tejidos", "category": "generales"},
    {"name": "ictericia", "description": "Coloración amarillenta de piel/ojos", "category": "digestivo"},
    {"name": "pérdida de apetito", "description": "Anorexia o inapetencia", "category": "digestivo"},
    {"name": "heces con sangre", "description": "Rectorragia o sangre en heces", "category": "digestivo"},
    {"name": "tos con sangre", "description": "Hemoptisis o expectoración con sangre", "category": "respiratorio"},
    {"name": "sudoración nocturna", "description": "Hiperhidrosis nocturna", "category": "generales"},
    {"name": "pérdida de peso", "description": "Pérdida de peso involuntaria", "category": "generales"},
    {"name": "comezón", "description": "Prurito o picazón en la piel", "category": "dermatologico"},
    {"name": "ojos rojos", "description": "Hiperemia conjuntival", "category": "oftalmologico"},
    {"name": "sensibilidad a la luz", "description": "Fotofobia", "category": "neurologico"},
    {"name": "dolor detrás de los ojos", "description": "Dolor retroorbitario", "category": "oftalmologico"},
    {"name": "mialgias", "description": "Dolores musculares generalizados", "category": "musculoesqueletico"},
    {"name": "orina turbia", "description": "Orina con aspecto turbio", "category": "urinario"},
    {"name": "orina maloliente", "description": "Orina con olor fuerte", "category": "urinario"},
    {"name": "urgencia urinaria", "description": "Necesidad imperiosa de orinar", "category": "urinario"},
    {"name": "petequias", "description": "Pequeñas manchas rojas en la piel", "category": "dermatologico"},
    {"name": "sangrado de encías", "description": "Sangrado gingival", "category": "generales"},
    {"name": "dolor abdominal intenso", "description": "Dolor abdominal severo", "category": "digestivo"},
    {"name": "fatiga extrema", "description": "Cansancio severo o agotamiento", "category": "generales"},
    {"name": "expectoración purulenta", "description": "Flema con pus", "category": "respiratorio"},
    {"name": "taquipnea", "description": "Frecuencia respiratoria elevada", "category": "respiratorio"},
    {"name": "cianosis", "description": "Coloración azulada de piel por falta de oxígeno", "category": "cardiovascular"},
    {"name": "expectoración", "description": "Flema o mucosidad expulsada al toser", "category": "respiratorio"},
    {"name": "sibilancias", "description": "Silbido al respirar", "category": "respiratorio"},
    {"name": "malestar general intenso", "description": "Sensación de enfermedad severa", "category": "generales"},
    {"name": "dolor ocular", "description": "Dolor en los ojos", "category": "oftalmologico"},
    {"name": "letargo", "description": "Somnolencia o falta de energía extrema", "category": "neurologico"},
    {"name": "convulsiones", "description": "Crisis convulsivas o ataques epilépticos", "category": "neurologico"},
    {"name": "signo de Kernig", "description": "Imposibilidad de extender la rodilla con cadera flexionada", "category": "neurologico"},
    {"name": "signo de Brudzinski", "description": "Flexión involuntaria de caderas al flexionar el cuello", "category": "neurologico"},
    {"name": "tos crónica (>3 semanas)", "description": "Tos persistente por más de 3 semanas", "category": "respiratorio"},
    {"name": "inflamación de amígdalas", "description": "Amígdalas rojas e inflamadas", "category": "respiratorio"},
    {"name": "exudado purulento", "description": "Secreción amarillenta de pus", "category": "generales"},
    {"name": "adenopatías cervicales", "description": "Ganglios inflamados en el cuello", "category": "generales"},
    {"name": "rinorrea acuosa", "description": "Secreción nasal líquida y clara", "category": "respiratorio"},
    {"name": "prurito nasal", "description": "Picazón dentro de la nariz", "category": "respiratorio"},
    {"name": "lagrimeo", "description": "Producción excesiva de lágrimas", "category": "oftalmologico"},
    {"name": "dificultad para tragar", "description": "Disfagia o dificultad al deglutir", "category": "digestivo"},
    {"name": "estornudos", "description": "Estornudos frecuentes", "category": "respiratorio"},
    {"name": "tenesmo", "description": "Sensación de evacuación incompleta", "category": "digestivo"},
    {"name": "irritabilidad", "description": "Estado de irritación o mal humor", "category": "neurologico"},
    {"name": "pérdida auditiva temporal", "description": "Disminución pasajera de la audición", "category": "otologico"},
    {"name": "sensación de oído tapado", "description": "Plenitud auricular", "category": "otologico"},
    {"name": "orina oscura", "description": "Orina de color oscuro como té o cola", "category": "urinario"},
    {"name": "heces pálidas", "description": "Heces de color arcilla o gris claro", "category": "digestivo"},
    {"name": "malestar general", "description": "Sensación inespecífica de enfermedad", "category": "generales"},
    {"name": "dolor torácico opresivo", "description": "Dolor en el pecho con sensación de presión", "category": "cardiovascular"},
    {"name": "dolor irradiado a brazo izquierdo", "description": "Dolor que se extiende al brazo izquierdo", "category": "cardiovascular"},
    {"name": "disnea", "description": "Falta de aire o dificultad respiratoria", "category": "respiratorio"},
    {"name": "sudoración profusa", "description": "Sudoración excesiva y abundante", "category": "generales"},
    {"name": "palpitaciones", "description": "Sensación de latidos cardíacos rápidos o fuertes", "category": "cardiovascular"},
    {"name": "ansiedad", "description": "Estado de preocupación o nerviosismo intenso", "category": "neurologico"},
    {"name": "dolor epigástrico", "description": "Dolor en la parte superior del abdomen", "category": "digestivo"},
    {"name": "síncope", "description": "Desmayo o pérdida breve de conciencia", "category": "neurologico"},
    {"name": "disnea de esfuerzo", "description": "Falta de aire al realizar actividad física", "category": "respiratorio"},
    {"name": "edema en piernas", "description": "Hinchazón en las extremidades inferiores", "category": "cardiovascular"},
    {"name": "taquipnea nocturna", "description": "Respiración rápida durante la noche", "category": "respiratorio"},
    {"name": "ortopnea", "description": "Dificultad para respirar al estar acostado", "category": "respiratorio"},
    {"name": "aumento de peso súbito", "description": "Ganancia rápida de peso por retención de líquidos", "category": "generales"},
    {"name": "tos nocturna", "description": "Tos que empeora durante la noche", "category": "respiratorio"},
    {"name": "disminución de la tolerancia al ejercicio", "description": "Menor capacidad para hacer actividad física", "category": "generales"},
    {"name": "dolor de cabeza occipital", "description": "Dolor en la parte posterior de la cabeza", "category": "neurologico"},
    {"name": "vértigo", "description": "Sensación de movimiento giratorio", "category": "neurologico"},
    {"name": "visión borrosa", "description": "Pérdida de nitidez visual", "category": "oftalmologico"},
    {"name": "zumbido de oídos", "description": "Tinnitus o pitidos en los oídos", "category": "otologico"},
    {"name": "epistaxis", "description": "Sangrado nasal", "category": "generales"},
    {"name": "enrojecimiento facial", "description": "Rubor o cara roja", "category": "dermatologico"},
    {"name": "poliuria", "description": "Producción excesiva de orina", "category": "urinario"},
    {"name": "polidipsia", "description": "Sed excesiva", "category": "generales"},
    {"name": "polifagia", "description": "Hambre excesiva o aumento del apetito", "category": "digestivo"},
    {"name": "pérdida de peso inexplicada", "description": "Pérdida de peso sin causa aparente", "category": "generales"},
    {"name": "infecciones frecuentes", "description": "Infecciones recurrentes", "category": "generales"},
    {"name": "cicatrización lenta", "description": "Heridas que tardan en sanar", "category": "generales"},
    {"name": "hormigueo en extremidades", "description": "Parestesia en brazos o piernas", "category": "neurologico"},
    {"name": "aumento de peso", "description": "Ganancia de peso involuntaria", "category": "generales"},
    {"name": "intolerancia al frío", "description": "Sensibilidad excesiva al frío", "category": "generales"},
    {"name": "piel seca", "description": "Piel descamada o reseca", "category": "dermatologico"},
    {"name": "caída de cabello", "description": "Alopecia o pérdida de cabello", "category": "dermatologico"},
    {"name": "estreñimiento", "description": "Dificultad para evacuar o heces duras", "category": "digestivo"},
    {"name": "bradicardia", "description": "Frecuencia cardíaca lenta (<60 lpm)", "category": "cardiovascular"},
    {"name": "depresión", "description": "Estado de ánimo bajo o tristeza persistente", "category": "neurologico"},
    {"name": "bocio", "description": "Aumento de tamaño de la glándula tiroides", "category": "endocrino"},
    {"name": "pérdida de peso con apetito aumentado", "description": "Adelgazamiento pese a comer más", "category": "endocrino"},
    {"name": "taquicardia", "description": "Frecuencia cardíaca acelerada (>100 lpm)", "category": "cardiovascular"},
    {"name": "intolerancia al calor", "description": "Sensibilidad excesiva al calor", "category": "generales"},
    {"name": "sudoración excesiva", "description": "Hiperhidrosis", "category": "generales"},
    {"name": "nerviosismo", "description": "Estado de agitación o inquietud", "category": "neurologico"},
    {"name": "temblores", "description": "Temblor fino en manos o dedos", "category": "neurologico"},
    {"name": "insomnio", "description": "Dificultad para dormir", "category": "neurologico"},
    {"name": "exoftalmos", "description": "Ojos saltones o protrusión ocular", "category": "oftalmologico"},
    {"name": "fatiga muscular", "description": "Debilidad en los músculos", "category": "musculoesqueletico"},
    {"name": "dolor de cabeza pulsátil unilateral", "description": "Dolor de cabeza como latido en un solo lado", "category": "neurologico"},
    {"name": "fotofobia", "description": "Molestia o intolerancia a la luz", "category": "neurologico"},
    {"name": "fonofobia", "description": "Molestia o intolerancia al ruido", "category": "neurologico"},
    {"name": "aura visual", "description": "Alucinaciones visuales previas a la migraña", "category": "neurologico"},
    {"name": "parestesias", "description": "Hormigueo o adormecimiento", "category": "neurologico"},
    {"name": "dolor empeora con actividad física", "description": "Dolor que aumenta con el movimiento", "category": "musculoesqueletico"},
    {"name": "debilidad facial unilateral", "description": "Parálisis o debilidad de un lado de la cara", "category": "neurologico"},
    {"name": "debilidad en extremidades", "description": "Pérdida de fuerza en brazos o piernas", "category": "neurologico"},
    {"name": "confusión súbita", "description": "Desorientación repentina", "category": "neurologico"},
    {"name": "dificultad para hablar", "description": "Disartria o dificultad para articular palabras", "category": "neurologico"},
    {"name": "pérdida de visión", "description": "Pérdida parcial o total de la vista", "category": "oftalmologico"},
    {"name": "dolor de cabeza súbito severo", "description": "Cefalea intensa de inicio repentino", "category": "neurologico"},
    {"name": "pérdida de equilibrio", "description": "Inestabilidad al caminar", "category": "neurologico"},
    {"name": "marcha inestable", "description": "Caminar con dificultad o tambaleo", "category": "neurologico"},
    {"name": "pérdida de conciencia", "description": "Pérdida del conocimiento o desmayo", "category": "neurologico"},
    {"name": "convulsiones tónico-clónicas", "description": "Movimientos violentos involuntarios de todo el cuerpo", "category": "neurologico"},
    {"name": "ausencias", "description": "Episodios breves de desconexión", "category": "neurologico"},
    {"name": "sacudidas mioclónicas", "description": "Movimientos musculares breves e involuntarios", "category": "neurologico"},
    {"name": "movimientos involuntarios", "description": "Movimientos anormales no controlados", "category": "neurologico"},
    {"name": "aura epigástrica", "description": "Sensación ascendente en el abdomen previa a crisis", "category": "neurologico"},
    {"name": "confusión postictal", "description": "Desorientación después de una convulsión", "category": "neurologico"},
    {"name": "mordedura de lengua", "description": "Herida en la lengua por mordedura durante convulsión", "category": "neurologico"},
    {"name": "temblor en reposo", "description": "Temblor que aparece cuando el miembro está en reposo", "category": "neurologico"},
    {"name": "rigidez muscular", "description": "Aumento del tono muscular", "category": "musculoesqueletico"},
    {"name": "bradicinesia", "description": "Lentitud de movimientos", "category": "neurologico"},
    {"name": "inestabilidad postural", "description": "Dificultad para mantener el equilibrio", "category": "neurologico"},
    {"name": "marcha arrastrada", "description": "Caminar arrastrando los pies", "category": "neurologico"},
    {"name": "micrografía", "description": "Letra pequeña y apretada", "category": "neurologico"},
    {"name": "hipomimia", "description": "Falta de expresión facial o cara de máscara", "category": "neurologico"},
    {"name": "disfagia", "description": "Dificultad para tragar", "category": "digestivo"},
    {"name": "deterioro cognitivo", "description": "Disminución de la capacidad mental", "category": "neurologico"},
    {"name": "dolor articular simétrico", "description": "Dolor en las mismas articulaciones de ambos lados", "category": "musculoesqueletico"},
    {"name": "rigidez matutina (>30 min)", "description": "Rigidez articular al despertar que dura más de 30 min", "category": "musculoesqueletico"},
    {"name": "inflamación articular", "description": "Articulaciones hinchadas", "category": "musculoesqueletico"},
    {"name": "nódulos reumatoides", "description": "Bultos subcutáneos cerca de articulaciones", "category": "musculoesqueletico"},
    {"name": "deformidad articular", "description": "Deformación visible de las articulaciones", "category": "musculoesqueletico"},
    {"name": "dolor a la palpación", "description": "Dolor al tocar o presionar", "category": "generales"},
    {"name": "erupción en mariposa facial", "description": "Rash facial con forma de mariposa", "category": "dermatologico"},
    {"name": "fotosensibilidad", "description": "Reacción exagerada de la piel al sol", "category": "dermatologico"},
    {"name": "úlceras orales", "description": "Llagas en la boca", "category": "digestivo"},
    {"name": "artritis", "description": "Inflamación de las articulaciones", "category": "musculoesqueletico"},
    {"name": "serositis", "description": "Inflamación de las membranas serosas", "category": "generales"},
    {"name": "nefritis", "description": "Inflamación del riñón", "category": "urinario"},
    {"name": "fenómeno de Raynaud", "description": "Cambio de coloración de dedos con el frío", "category": "cardiovascular"},
    {"name": "fiebre cíclica con escalofríos", "description": "Fiebre que aparece en ciclos con temblores", "category": "generales"},
    {"name": "dolor de cabeza intenso", "description": "Cefalea severa", "category": "neurologico"},
    {"name": "hepatomegalia", "description": "Aumento del tamaño del hígado", "category": "digestivo"},
    {"name": "esplenomegalia", "description": "Aumento del tamaño del bazo", "category": "digestivo"},
    {"name": "fiebre elevada escalonada", "description": "Fiebre que sube gradualmente en días", "category": "generales"},
    {"name": "cefalea frontal", "description": "Dolor de cabeza en la región frontal", "category": "neurologico"},
    {"name": "bradicardia relativa", "description": "Frecuencia cardíaca baja para la fiebre presente", "category": "cardiovascular"},
    {"name": "manchas rosadas en tronco", "description": "Rash de color rosado en el torso", "category": "dermatologico"},
    {"name": "estreñimiento o diarrea", "description": "Alteración del ritmo intestinal", "category": "digestivo"},
    {"name": "hepatoesplenomegalia", "description": "Aumento de tamaño de hígado y bazo", "category": "digestivo"},
    {"name": "exantema vesicular pruriginoso", "description": "Erupción con ampollas que pican", "category": "dermatologico"},
    {"name": "vesículas en diferentes estadios", "description": "Ampollas en distintas etapas de evolución", "category": "dermatologico"},
    {"name": "lesiones en cuero cabelludo", "description": "Lesiones cutáneas en el cuero cabelludo", "category": "dermatologico"},
    {"name": "erupción vesicular dermatomal", "description": "Ampollas siguiendo un dermatoma nervioso", "category": "dermatologico"},
    {"name": "dolor urente o punzante", "description": "Dolor como quemadura o pinchazo", "category": "neurologico"},
    {"name": "hipersensibilidad de la piel", "description": "Piel sensible al tacto", "category": "dermatologico"},
    {"name": "prurito", "description": "Picazón", "category": "dermatologico"},
    {"name": "faringitis", "description": "Inflamación de la faringe", "category": "respiratorio"},
    {"name": "linfadenopatía generalizada", "description": "Ganglios inflamados en todo el cuerpo", "category": "generales"},
    {"name": "artralgias", "description": "Dolor en las articulaciones", "category": "musculoesqueletico"},
    {"name": "rash maculopapular", "description": "Erupción cutánea con manchas y pápulas", "category": "dermatologico"},
    {"name": "úlceras orales o genitales", "description": "Llagas en boca o genitales", "category": "dermatologico"},
    {"name": "fatiga severa", "description": "Cansancio extremo", "category": "generales"},
    {"name": "linfadenopatía cervical posterior", "description": "Ganglios inflamados en la parte trasera del cuello", "category": "generales"},
    {"name": "faringitis exudativa", "description": "Inflamación faríngea con secreción purulenta", "category": "respiratorio"},
    {"name": "rash máculo-papular", "description": "Erupción con manchas planas y elevadas", "category": "dermatologico"},
    {"name": "cefalea severa", "description": "Dolor de cabeza muy intenso", "category": "neurologico"},
    {"name": "mialgias (especialmente gemelares)", "description": "Dolor muscular en las pantorrillas", "category": "musculoesqueletico"},
    {"name": "inyección conjuntival", "description": "Ojos rojos por vasos dilatados", "category": "oftalmologico"},
    {"name": "insuficiencia renal", "description": "Falla de la función renal", "category": "urinario"},
    {"name": "hemorragias", "description": "Sangrados activos", "category": "generales"},
    {"name": "congestión pulmonar", "description": "Acumulación de líquido en los pulmones", "category": "respiratorio"},
    {"name": "fiebre ondulante", "description": "Fiebre que sube y baja en ondas", "category": "generales"},
    {"name": "opresión torácica", "description": "Sensación de presión en el pecho", "category": "cardiovascular"},
    {"name": "empeoramiento nocturno o matutino", "description": "Síntomas que empeoran de noche o al amanecer", "category": "respiratorio"},
    {"name": "respiración corta", "description": "Respiración superficial y rápida", "category": "respiratorio"},
    {"name": "uso de musculatura accesoria", "description": "Usar músculos del cuello y hombros para respirar", "category": "respiratorio"},
    {"name": "disnea progresiva", "description": "Falta de aire que empeora con el tiempo", "category": "respiratorio"},
    {"name": "tos crónica", "description": "Tos persistente por mucho tiempo", "category": "respiratorio"},
    {"name": "infecciones respiratorias recurrentes", "description": "Infecciones frecuentes de las vías respiratorias", "category": "respiratorio"},
    {"name": "disfonía o afonía", "description": "Ronquera o pérdida de la voz", "category": "respiratorio"},
    {"name": "tos seca", "description": "Tos sin producción de flema", "category": "respiratorio"},
    {"name": "sensación de cuerpo extraño en garganta", "description": "Sensación de tener algo atorado en la garganta", "category": "respiratorio"},
    {"name": "fiebre leve", "description": "Temperatura ligeramente elevada (<38°C)", "category": "generales"},
    {"name": "odinofagia", "description": "Dolor al tragar", "category": "respiratorio"},
    {"name": "edema de cuerdas vocales", "description": "Hinchazón de las cuerdas vocales", "category": "respiratorio"},
    {"name": "dolor abdominal periumbilical que migra a fosa ilíaca derecha", "description": "Dolor que empieza en el ombligo y se mueve al lado derecho bajo", "category": "digestivo"},
    {"name": "defensa abdominal", "description": "Tensión involuntaria de los músculos abdominales", "category": "digestivo"},
    {"name": "signo de Blumberg", "description": "Dolor al soltar la presión en el abdomen", "category": "digestivo"},
    {"name": "signo de Rovsing", "description": "Dolor en lado derecho al presionar lado izquierdo", "category": "digestivo"},
    {"name": "dolor en hipocondrio derecho", "description": "Dolor en la parte superior derecha del abdomen", "category": "digestivo"},
    {"name": "signo de Murphy", "description": "Dolor al presionar la vesícula biliar al inhalar", "category": "digestivo"},
    {"name": "dolor irradiado a hombro derecho", "description": "Dolor que se extiende al hombro derecho", "category": "digestivo"},
    {"name": "ictericia leve", "description": "Coloración amarillenta leve de la piel", "category": "digestivo"},
    {"name": "distensión abdominal", "description": "Abdomen inflamado o hinchado", "category": "digestivo"},
    {"name": "dolor abdominal epigástrico quemante", "description": "Ardor en la boca del estómago", "category": "digestivo"},
    {"name": "dolor alivia con alimentos", "description": "Dolor que mejora al comer", "category": "digestivo"},
    {"name": "dolor nocturno", "description": "Dolor que aparece durante la noche", "category": "digestivo"},
    {"name": "hematemesis", "description": "Vómito con sangre", "category": "digestivo"},
    {"name": "melena", "description": "Heces negras por sangre digerida", "category": "digestivo"},
    {"name": "saciedad temprana", "description": "Sensación de llenura al comer poco", "category": "digestivo"},
    {"name": "acidez retroesternal", "description": "Ardor en el pecho", "category": "digestivo"},
    {"name": "regurgitación ácida", "description": "Devolución de contenido ácido a la boca", "category": "digestivo"},
    {"name": "ronquera matutina", "description": "Voz ronca al despertar", "category": "respiratorio"},
    {"name": "sensación de globo faríngeo", "description": "Sensación de nudo en la garganta", "category": "digestivo"},
    {"name": "erosión dental", "description": "Desgaste del esmalte dental por ácido", "category": "digestivo"},
    {"name": "dolor lumbar intenso unilateral", "description": "Dolor fuerte en un lado de la espalda baja", "category": "musculoesqueletico"},
    {"name": "dolor irradiado a genitales", "description": "Dolor que se extiende a los genitales", "category": "urinario"},
    {"name": "inquietud extrema", "description": "Incapacidad de estar quieto por el dolor", "category": "neurologico"},
    {"name": "hematuria", "description": "Sangre en la orina", "category": "urinario"},
    {"name": "disuria", "description": "Dolor o dificultad al orinar", "category": "urinario"},
    {"name": "disminución de la diuresis", "description": "Reducción del volumen de orina", "category": "urinario"},
    {"name": "edema generalizado", "description": "Hinchazón en todo el cuerpo", "category": "generales"},
    {"name": "hipertensión arterial", "description": "Presión arterial elevada", "category": "cardiovascular"},
    {"name": "hiperkalemia", "description": "Potasio elevado en sangre", "category": "generales"},
    {"name": "asterixis", "description": "Temblor en las manos al extender las muñecas", "category": "neurologico"},
    {"name": "eritema localizado", "description": "Enrojecimiento de la piel en un área", "category": "dermatologico"},
    {"name": "calor local", "description": "Aumento de temperatura en la piel", "category": "dermatologico"},
    {"name": "edema", "description": "Hinchazón por acumulación de líquido", "category": "generales"},
    {"name": "ampollas", "description": "Vesículas llenas de líquido", "category": "dermatologico"},
    {"name": "linfangitis", "description": "Inflamación de los vasos linfáticos", "category": "dermatologico"},
    {"name": "linfadenopatía regional", "description": "Ganglios inflamados cerca del área afectada", "category": "generales"},
    {"name": "habones eritematosos", "description": "Ronchas rojas en la piel", "category": "dermatologico"},
    {"name": "prurito intenso", "description": "Picazón severa", "category": "dermatologico"},
    {"name": "edema angioneurótico", "description": "Hinchazón profunda de la piel y mucosas", "category": "dermatologico"},
    {"name": "lesiones evanescentes (<24h)", "description": "Lesiones que desaparecen en menos de 24 horas", "category": "dermatologico"},
    {"name": "dermografismo", "description": "Ronchas que aparecen al rascar la piel", "category": "dermatologico"},
    {"name": "palidez del centro de las lesiones", "description": "Centro pálido rodeado de enrojecimiento", "category": "dermatologico"},
    {"name": "sensación de ardor", "description": "Sensación de quemadura en la piel", "category": "dermatologico"},
    {"name": "liquenificación", "description": "Engrosamiento de la piel por rascado crónico", "category": "dermatologico"},
    {"name": "exudación y costras", "description": "Supuración con formación de costras", "category": "dermatologico"},
    {"name": "lesiones flexurales", "description": "Lesiones en pliegues de la piel", "category": "dermatologico"},
    {"name": "xerosis", "description": "Sequedad excesiva de la piel", "category": "dermatologico"},
    {"name": "alteración del sueño por prurito", "description": "Problemas para dormir por picazón", "category": "dermatologico"},
    {"name": "dolor suprapúbico", "description": "Dolor sobre el pubis", "category": "urinario"},
    {"name": "frecuencia urinaria diurna y nocturna", "description": "Orinar frecuentemente día y noche", "category": "urinario"},
    {"name": "dolor al llenar la vejiga", "description": "Dolor al acumularse la orina", "category": "urinario"},
    {"name": "alivio con vaciamiento", "description": "Mejoría del dolor al orinar", "category": "urinario"},
    {"name": "dispareunia", "description": "Dolor durante las relaciones sexuales", "category": "urinario"},
    {"name": "dolor musculoesquelético generalizado", "description": "Dolor en músculos y huesos de todo el cuerpo", "category": "musculoesqueletico"},
    {"name": "trastornos del sueño", "description": "Dificultad para conciliar o mantener el sueño", "category": "neurologico"},
    {"name": "rigidez matutina", "description": "Rigidez articular al despertar", "category": "musculoesqueletico"},
    {"name": "síndrome de colon irritable", "description": "Trastorno digestivo con dolor y alteración del ritmo", "category": "digestivo"},
    {"name": "dificultades cognitivas", "description": "Problemas de concentración o memoria", "category": "neurologico"},
]

diseases = [
    {
        "name": "Influenza (Gripe)",
        "description": "Infección viral respiratoria aguda causada por el virus de la influenza",
        "symptoms": ["fiebre", "tos", "dolor de cabeza", "fatiga", "dolor de garganta", "congestión nasal", "escalofríos", "dolor muscular", "malestar general intenso", "pérdida de apetito", "dolor ocular"],
        "severity": "moderate",
    },
    {
        "name": "Resfriado Común",
        "description": "Infección viral leve del tracto respiratorio superior",
        "symptoms": ["tos", "dolor de garganta", "congestión nasal", "dolor de cabeza", "fatiga", "estornudos", "rinorrea"],
        "severity": "mild",
    },
    {
        "name": "COVID-19",
        "description": "Enfermedad infecciosa causada por el coronavirus SARS-CoV-2",
        "symptoms": ["fiebre", "tos", "fatiga", "pérdida del gusto", "pérdida del olfato", "dolor de cabeza", "dolor de garganta", "dificultad para respirar", "mialgias", "diarrea", "congestión nasal", "escalofríos"],
        "severity": "high",
    },
    {
        "name": "Gastroenteritis Aguda",
        "description": "Inflamación del estómago e intestinos, comúnmente por infección viral o bacteriana",
        "symptoms": ["diarrea", "náuseas", "vómito", "dolor abdominal", "fiebre", "fatiga", "deshidratación", "pérdida de apetito", "dolor muscular"],
        "severity": "moderate",
    },
    {
        "name": "Neumonía",
        "description": "Infección pulmonar que inflama los alvéolos, puede ser bacteriana o viral",
        "symptoms": ["fiebre", "tos", "dificultad para respirar", "dolor en el pecho", "escalofríos", "fatiga", "expectoración purulenta", "taquipnea", "cianosis"],
        "severity": "high",
    },
    {
        "name": "Otitis Media",
        "description": "Infección del oído medio, común en niños",
        "symptoms": ["dolor de oído", "fiebre", "secreción del oído", "dolor de cabeza", "irritabilidad", "pérdida auditiva temporal", "sensación de oído tapado"],
        "severity": "moderate",
    },
    {
        "name": "Infección Urinaria",
        "description": "Infección del tracto urinario, generalmente bacteriana",
        "symptoms": ["ardor al orinar", "frecuencia urinaria", "dolor abdominal", "fiebre", "dolor lumbar", "orina turbia", "orina maloliente", "urgencia urinaria", "escalofríos"],
        "severity": "moderate",
    },
    {
        "name": "Dengue",
        "description": "Enfermedad viral transmitida por mosquitos Aedes",
        "symptoms": ["fiebre alta persistente", "dolor de cabeza", "dolor muscular", "dolor articular", "dolor detrás de los ojos", "sarpullido", "náuseas", "vómito", "petequias", "sangrado de encías", "dolor abdominal intenso", "fatiga extrema"],
        "severity": "high",
    },
    {
        "name": "Meningitis",
        "description": "Inflamación de las membranas que recubren el cerebro y la médula espinal",
        "symptoms": ["fiebre", "dolor de cabeza", "rigidez de cuello", "confusión", "náuseas", "vómito", "sensibilidad a la luz", "letargo", "convulsiones", "signo de Kernig", "signo de Brudzinski"],
        "severity": "critical",
    },
    {
        "name": "Hepatitis A",
        "description": "Infección viral del hígado transmitida por alimentos o agua contaminados",
        "symptoms": ["fatiga", "pérdida de apetito", "ictericia", "dolor abdominal", "náuseas", "fiebre", "orina oscura", "heces pálidas", "malestar general", "dolor articular"],
        "severity": "moderate",
    },
    {
        "name": "Bronquitis Aguda",
        "description": "Inflamación de los bronquios, generalmente por infección viral",
        "symptoms": ["tos", "fatiga", "dificultad para respirar", "dolor en el pecho", "fiebre", "dolor de garganta", "expectoración", "sibilancias"],
        "severity": "moderate",
    },
    {
        "name": "Amigdalitis",
        "description": "Infección e inflamación de las amígdalas",
        "symptoms": ["dolor de garganta", "fiebre", "dolor de cabeza", "fatiga", "dificultad para tragar", "inflamación de amígdalas", "exudado purulento", "adenopatías cervicales"],
        "severity": "moderate",
    },
    {
        "name": "Rinitis Alérgica",
        "description": "Reacción alérgica que causa inflamación nasal",
        "symptoms": ["congestión nasal", "estornudos", "ojos rojos", "comezón", "rinorrea acuosa", "prurito nasal", "lagrimeo"],
        "severity": "mild",
    },
    {
        "name": "Intoxicación Alimentaria",
        "description": "Enfermedad causada por consumir alimentos contaminados",
        "symptoms": ["diarrea", "vómito", "dolor abdominal", "náuseas", "fiebre", "deshidratación", "escalofríos", "heces con sangre"],
        "severity": "moderate",
    },
    {
        "name": "Tuberculosis",
        "description": "Infección bacteriana pulmonar grave causada por Mycobacterium tuberculosis",
        "symptoms": ["tos con sangre", "sudoración nocturna", "pérdida de peso", "fiebre", "fatiga", "dolor en el pecho", "tos crónica (>3 semanas)", "expectoración", "escalofríos"],
        "severity": "critical",
    },
    {
        "name": "Shigelosis (Disentería)",
        "description": "Infección bacteriana intestinal que causa diarrea con sangre",
        "symptoms": ["diarrea", "heces con sangre", "fiebre", "dolor abdominal", "náuseas", "deshidratación", "tenesmo", "escalofríos"],
        "severity": "high",
    },
    {
        "name": "Infarto Agudo de Miocardio",
        "description": "Necrosis del miocardio por isquemia prolongada",
        "symptoms": ["dolor torácico opresivo", "dolor irradiado a brazo izquierdo", "disnea", "náuseas", "vómito", "sudoración profusa", "palpitaciones", "ansiedad", "dolor epigástrico", "fatiga extrema", "síncope"],
        "severity": "critical",
    },
    {
        "name": "Insuficiencia Cardíaca",
        "description": "Incapacidad del corazón para bombear sangre adecuadamente",
        "symptoms": ["disnea de esfuerzo", "fatiga", "edema en piernas", "taquipnea nocturna", "ortopnea", "aumento de peso súbito", "tos nocturna", "palpitaciones", "disminución de la tolerancia al ejercicio"],
        "severity": "high",
    },
    {
        "name": "Hipertensión Arterial",
        "description": "Presión arterial elevada crónica",
        "symptoms": ["dolor de cabeza occipital", "vértigo", "visión borrosa", "zumbido de oídos", "epistaxis", "fatiga", "palpitaciones", "enrojecimiento facial"],
        "severity": "moderate",
    },
    {
        "name": "Diabetes Mellitus Tipo 2",
        "description": "Trastorno metabólico con hiperglucemia crónica",
        "symptoms": ["poliuria", "polidipsia", "polifagia", "pérdida de peso inexplicada", "fatiga", "visión borrosa", "infecciones frecuentes", "cicatrización lenta", "hormigueo en extremidades"],
        "severity": "high",
    },
    {
        "name": "Hipotiroidismo",
        "description": "Disminución de la función tiroidea",
        "symptoms": ["fatiga extrema", "aumento de peso", "intolerancia al frío", "piel seca", "caída de cabello", "estreñimiento", "bradicardia", "depresión", "letargo", "bocio"],
        "severity": "moderate",
    },
    {
        "name": "Hipertiroidismo",
        "description": "Producción excesiva de hormonas tiroideas",
        "symptoms": ["pérdida de peso con apetito aumentado", "taquicardia", "intolerancia al calor", "sudoración excesiva", "nerviosismo", "temblores", "insomnio", "exoftalmos", "bocio", "fatiga muscular"],
        "severity": "moderate",
    },
    {
        "name": "Migraña",
        "description": "Cefalea primaria con aura o sin aura",
        "symptoms": ["dolor de cabeza pulsátil unilateral", "fotofobia", "fonofobia", "náuseas", "vómito", "aura visual", "parestesias", "dolor empeora con actividad física"],
        "severity": "moderate",
    },
    {
        "name": "Accidente Cerebrovascular (ACV)",
        "description": "Interrupción súbita del flujo sanguíneo cerebral",
        "symptoms": ["debilidad facial unilateral", "debilidad en extremidades", "confusión súbita", "dificultad para hablar", "pérdida de visión", "dolor de cabeza súbito severo", "pérdida de equilibrio", "marcha inestable", "pérdida de conciencia"],
        "severity": "critical",
    },
    {
        "name": "Epilepsia",
        "description": "Trastorno neurológico con convulsiones recurrentes",
        "symptoms": ["convulsiones tónico-clónicas", "ausencias", "sacudidas mioclónicas", "movimientos involuntarios", "pérdida de conciencia", "aura epigástrica", "confusión postictal", "mordedura de lengua"],
        "severity": "high",
    },
    {
        "name": "Enfermedad de Parkinson",
        "description": "Trastorno neurodegenerativo del movimiento",
        "symptoms": ["temblor en reposo", "rigidez muscular", "bradicinesia", "inestabilidad postural", "marcha arrastrada", "micrografía", "hipomimia", "disfagia", "depresión", "deterioro cognitivo"],
        "severity": "moderate",
    },
    {
        "name": "Artritis Reumatoide",
        "description": "Enfermedad autoinmune inflamatoria crónica de articulaciones",
        "symptoms": ["dolor articular simétrico", "rigidez matutina (>30 min)", "inflamación articular", "fatiga", "fiebre", "pérdida de peso", "nódulos reumatoides", "deformidad articular", "dolor a la palpación"],
        "severity": "high",
    },
    {
        "name": "Lupus Eritematoso Sistémico",
        "description": "Enfermedad autoinmune multisistémica",
        "symptoms": ["erupción en mariposa facial", "fotosensibilidad", "úlceras orales", "artritis", "serositis", "nefritis", "fatiga extrema", "fiebre", "caída de cabello", "fenómeno de Raynaud"],
        "severity": "high",
    },
    {
        "name": "Malaria",
        "description": "Enfermedad parasitaria transmitida por mosquito Anopheles",
        "symptoms": ["fiebre cíclica con escalofríos", "sudoración profusa", "dolor de cabeza intenso", "dolor muscular", "fatiga extrema", "náuseas", "vómito", "ictericia", "hepatomegalia", "esplenomegalia"],
        "severity": "high",
    },
    {
        "name": "Fiebre Tifoidea",
        "description": "Infección bacteriana sistémica por Salmonella typhi",
        "symptoms": ["fiebre elevada escalonada", "dolor abdominal", "cefalea frontal", "bradicardia relativa", "manchas rosadas en tronco", "estreñimiento o diarrea", "hepatoesplenomegalia", "letargo"],
        "severity": "high",
    },
    {
        "name": "Varicela",
        "description": "Infección viral aguda por virus varicela-zóster",
        "symptoms": ["exantema vesicular pruriginoso", "fiebre", "fatiga", "dolor de cabeza", "pérdida de apetito", "vesículas en diferentes estadios", "lesiones en cuero cabelludo"],
        "severity": "moderate",
    },
    {
        "name": "Herpes Zóster",
        "description": "Reactivación del virus varicela-zóster en nervios",
        "symptoms": ["erupción vesicular dermatomal", "dolor urente o punzante", "parestesia", "fiebre", "cefalea", "malestar general", "hipersensibilidad de la piel", "prurito"],
        "severity": "moderate",
    },
    {
        "name": "VIH (Infección Aguda)",
        "description": "Infección inicial por virus de inmunodeficiencia humana",
        "symptoms": ["fiebre", "fatiga", "faringitis", "linfadenopatía generalizada", "cefalea", "mialgias", "artralgias", "náuseas", "diarrea", "rash maculopapular", "úlceras orales o genitales"],
        "severity": "moderate",
    },
    {
        "name": "Mononucleosis Infecciosa",
        "description": "Infección viral por Epstein-Barr",
        "symptoms": ["fatiga severa", "fiebre", "linfadenopatía cervical posterior", "faringitis exudativa", "esplenomegalia", "hepatomegalia", "cefalea", "rash máculo-papular", "sudoración nocturna"],
        "severity": "moderate",
    },
    {
        "name": "Leptospirosis",
        "description": "Infección bacteriana transmitida por agua contaminada con orina de animales",
        "symptoms": ["fiebre", "cefalea severa", "mialgias (especialmente gemelares)", "inyección conjuntival", "dolor abdominal", "vómito", "ictericia", "insuficiencia renal", "hemorragias", "congestión pulmonar"],
        "severity": "high",
    },
    {
        "name": "Brucelosis",
        "description": "Infección bacteriana por Brucella transmitida por animales",
        "symptoms": ["fiebre ondulante", "sudoración profusa", "fatiga extrema", "cefalea", "dolor lumbar", "artralgias", "esplenomegalia", "linfadenopatía", "pérdida de peso", "hepatomegalia"],
        "severity": "moderate",
    },
    {
        "name": "Asma Bronquial",
        "description": "Enfermedad inflamatoria crónica de la vía aérea",
        "symptoms": ["sibilancias", "disnea", "tos seca", "opresión torácica", "empeoramiento nocturno o matutino", "respiración corta", "uso de musculatura accesoria", "taquipnea"],
        "severity": "moderate",
    },
    {
        "name": "EPOC",
        "description": "Enfermedad pulmonar obstructiva crónica",
        "symptoms": ["disnea progresiva", "tos crónica", "expectoración", "sibilancias", "fatiga", "pérdida de peso", "infecciones respiratorias recurrentes", "cianosis"],
        "severity": "high",
    },
    {
        "name": "Laringitis Aguda",
        "description": "Inflamación aguda de la laringe",
        "symptoms": ["disfonía o afonía", "dolor de garganta", "tos seca", "sensación de cuerpo extraño en garganta", "fiebre leve", "odinofagia", "edema de cuerdas vocales"],
        "severity": "mild",
    },
    {
        "name": "Apendicitis Aguda",
        "description": "Inflamación aguda del apéndice cecal",
        "symptoms": ["dolor abdominal periumbilical que migra a fosa ilíaca derecha", "náuseas", "vómito", "pérdida de apetito", "fiebre", "defensa abdominal", "signo de Blumberg", "signo de Rovsing"],
        "severity": "high",
    },
    {
        "name": "Colecistitis",
        "description": "Inflamación aguda de la vesícula biliar",
        "symptoms": ["dolor en hipocondrio derecho", "fiebre", "náuseas", "vómito", "signo de Murphy", "dolor irradiado a hombro derecho", "ictericia leve", "distensión abdominal"],
        "severity": "high",
    },
    {
        "name": "Úlcera Péptica",
        "description": "Lesión erosiva en mucosa gástrica o duodenal",
        "symptoms": ["dolor abdominal epigástrico quemante", "dolor alivia con alimentos", "dolor nocturno", "náuseas", "pérdida de peso", "hematemesis", "melena", "saciedad temprana", "distensión abdominal"],
        "severity": "moderate",
    },
    {
        "name": "Reflujo Gastroesofágico (ERGE)",
        "description": "Retorno anormal del contenido gástrico al esófago",
        "symptoms": ["acidez retroesternal", "regurgitación ácida", "dolor torácico", "disfagia", "tos crónica", "ronquera matutina", "sensación de globo faríngeo", "erosión dental"],
        "severity": "mild",
    },
    {
        "name": "Cólico Nefrítico",
        "description": "Dolor por obstrucción aguda del tracto urinario por cálculo",
        "symptoms": ["dolor lumbar intenso unilateral", "dolor irradiado a genitales", "inquietud extrema", "náuseas", "vómito", "hematuria", "disuria"],
        "severity": "moderate",
    },
    {
        "name": "Insuficiencia Renal Aguda",
        "description": "Pérdida súbita de la función renal",
        "symptoms": ["disminución de la diuresis", "edema generalizado", "fatiga", "confusión", "náuseas", "vómito", "disnea", "hipertensión arterial", "hiperkalemia", "asterixis", "convulsiones"],
        "severity": "critical",
    },
    {
        "name": "Celulitis",
        "description": "Infección bacteriana de la piel y tejido subcutáneo",
        "symptoms": ["eritema localizado", "calor local", "dolor", "edema", "fiebre", "escalofríos", "ampollas", "linfangitis", "linfadenopatía regional", "malestar general"],
        "severity": "moderate",
    },
    {
        "name": "Urticaria",
        "description": "Reacción cutánea con ronchas pruriginosas transitorias",
        "symptoms": ["habones eritematosos", "prurito intenso", "edema angioneurótico", "lesiones evanescentes (<24h)", "dermografismo", "palidez del centro de las lesiones", "sensación de ardor"],
        "severity": "mild",
    },
    {
        "name": "Dermatitis Atópica",
        "description": "Enfermedad inflamatoria crónica de la piel de origen inmune",
        "symptoms": ["prurito intenso", "piel seca", "eritema", "liquenificación", "exudación y costras", "lesiones flexurales", "xerosis", "alteración del sueño por prurito"],
        "severity": "moderate",
    },
    {
        "name": "Cistitis Intersticial",
        "description": "Inflamación crónica de la vejiga sin causa infecciosa",
        "symptoms": ["dolor suprapúbico", "frecuencia urinaria diurna y nocturna", "urgencia urinaria", "dolor al llenar la vejiga", "alivio con vaciamiento", "dispareunia", "fatiga"],
        "severity": "moderate",
    },
    {
        "name": "Fibromialgia",
        "description": "Trastorno de dolor crónico generalizado",
        "symptoms": ["dolor musculoesquelético generalizado", "fatiga severa", "trastornos del sueño", "rigidez matutina", "cefalea", "síndrome de colon irritable", "dificultades cognitivas", "parestesias", "depresión", "ansiedad"],
        "severity": "moderate",
    },
]

treatments = [
    {
        "disease_name": "Influenza (Gripe)",
        "medicines": [
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas", "duration": "5 días"},
            {"name": "Oseltamivir 75mg", "dosage": "75mg", "frequency": "Cada 12 horas", "duration": "5 días"},
            {"name": "Loratadina 10mg", "dosage": "10mg", "frequency": "Cada 24 horas", "duration": "5 días"},
        ],
        "general_recommendations": "Reposo, hidratación abundante, evitar cambios bruscos de temperatura. Acudir a urgencias si hay dificultad para respirar.",
    },
    {
        "disease_name": "Resfriado Común",
        "medicines": [
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas", "duration": "3-5 días"},
            {"name": "Descongestionante nasal (Pseudoefedrina)", "dosage": "30mg", "frequency": "Cada 12 horas", "duration": "3 días"},
            {"name": "Vitamina C 500mg", "dosage": "500mg", "frequency": "Cada 24 horas", "duration": "7 días"},
        ],
        "general_recommendations": "Reposo, hidratación, miel con limón para la garganta. No requiere antibióticos.",
    },
    {
        "disease_name": "COVID-19",
        "medicines": [
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 6-8 horas", "duration": "Según síntomas"},
            {"name": "Paxlovid (Nirmatrelvir/Ritonavir)", "dosage": "300mg/100mg", "frequency": "Cada 12 horas", "duration": "5 días"},
            {"name": "Dexametasona 6mg", "dosage": "6mg", "frequency": "Cada 24 horas", "duration": "10 días"},
            {"name": "Enoxaparina 40mg", "dosage": "40mg", "frequency": "Cada 24 horas SQ", "duration": "Durante hospitalización"},
        ],
        "general_recommendations": "Aislamiento obligatorio. Monitoreo de saturación de oxígeno. Acudir a urgencias si saturación <90% o dificultad respiratoria severa.",
    },
    {
        "disease_name": "Gastroenteritis Aguda",
        "medicines": [
            {"name": "Solución de rehidratación oral", "dosage": "1L", "frequency": "A demanda, pequeños sorbos", "duration": "Durante cuadro"},
            {"name": "Lactobacillus (probiótico)", "dosage": "1 sobre", "frequency": "Cada 12 horas", "duration": "7 días"},
            {"name": "Loperamida 2mg", "dosage": "2mg", "frequency": "Después de cada evacuación (máx 8mg/día)", "duration": "Máx 2 días"},
        ],
        "general_recommendations": "Dieta blanda (arroz, manzana, zanahoria reposo GI). Suspender lácteos temporalmente. Signos de alarma: fiebre >39°C o heces con sangre.",
    },
    {
        "disease_name": "Neumonía",
        "medicines": [
            {"name": "Amoxicilina 500mg", "dosage": "500mg", "frequency": "Cada 8 horas", "duration": "10 días"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas", "duration": "5 días"},
            {"name": "Salbutamol inhalador", "dosage": "2 inhalaciones", "frequency": "Cada 6-8 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "REQUIERE HOSPITALIZACIÓN si saturación <92%. Fisioterapia respiratoria. Oxígeno suplementario si es necesario.",
    },
    {
        "disease_name": "Otitis Media",
        "medicines": [
            {"name": "Amoxicilina 250-500mg", "dosage": "250-500mg", "frequency": "Cada 8 horas", "duration": "7-10 días"},
            {"name": "Ibuprofeno 400mg", "dosage": "400mg", "frequency": "Cada 8 horas", "duration": "5 días"},
            {"name": "Gotas óticas (antimicrobianas)", "dosage": "3 gotas", "frequency": "Cada 8 horas", "duration": "7 días"},
        ],
        "general_recommendations": "Evitar entrada de agua en el oído. No introducir objetos. Evaluar por ORL si recurrente.",
    },
    {
        "disease_name": "Infección Urinaria",
        "medicines": [
            {"name": "Fosfomicina trometamol 3g", "dosage": "3g", "frequency": "Dosis única", "duration": "1 dosis"},
            {"name": "Ibuprofeno 400mg", "dosage": "400mg", "frequency": "Cada 8 horas PRN", "duration": "3 días"},
        ],
        "general_recommendations": "Aumentar ingesta de agua (>2L/día). Urocultivo si es recurrente. Evaluar por urología si más de 3 infecciones al año.",
    },
    {
        "disease_name": "Dengue",
        "medicines": [
            {"name": "Acetaminofén 500mg", "dosage": "500mg", "frequency": "Cada 6 horas", "duration": "5 días"},
            {"name": "Solución de rehidratación oral", "dosage": "1-2L", "frequency": "A demanda", "duration": "Durante cuadro"},
        ],
        "general_recommendations": "NO USAR AINES (ibuprofeno, aspirina) por riesgo de sangrado. Reposo absoluto. Monitorear signos de alarma: dolor abdominal intenso, vómitos persistentes, sangrado de encías. Acudir a urgencias de inmediato si presenta signos de alarma.",
    },
    {
        "disease_name": "Meningitis",
        "medicines": [
            {"name": "Ceftriaxona 2g IV", "dosage": "2g", "frequency": "Cada 12 horas IV", "duration": "14 días"},
            {"name": "Dexametasona 0.15mg/kg IV", "dosage": "0.15mg/kg", "frequency": "Cada 6 horas IV", "duration": "4 días"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 6 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "EMERGENCIA MÉDICA - Hospitalización inmediata. Punción lumbar para diagnóstico. Aislamiento respiratorio. Monitoreo neurológico estricto.",
    },
    {
        "disease_name": "Hepatitis A",
        "medicines": [],
        "general_recommendations": "Reposo absoluto. Dieta baja en grasas. Evitar alcohol por 6 meses. Hidratación. La mayoría se resuelve sola en 2-4 semanas. No hay tratamiento antiviral específico. Vacunación para contactos.",
    },
    {
        "disease_name": "Bronquitis Aguda",
        "medicines": [
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas", "duration": "5 días"},
            {"name": "Salbutamol inhalador", "dosage": "2 inhalaciones", "frequency": "Cada 6-8 horas PRN", "duration": "Según síntomas"},
            {"name": "Acetilcisteína 600mg", "dosage": "600mg", "frequency": "Cada 24 horas", "duration": "7 días"},
        ],
        "general_recommendations": "No requiere antibióticos a menos que se sospeche infección bacteriana. Nebulizaciones con solución salina. Evitar irritantes como humo de tabaco.",
    },
    {
        "disease_name": "Amigdalitis",
        "medicines": [
            {"name": "Amoxicilina 500mg", "dosage": "500mg", "frequency": "Cada 8 horas", "duration": "7-10 días"},
            {"name": "Ibuprofeno 400mg", "dosage": "400mg", "frequency": "Cada 8 horas", "duration": "5 días"},
            {"name": "Gárgaras con solución salina", "dosage": "Vaso de agua tibia + sal", "frequency": "Cada 6 horas", "duration": "5 días"},
        ],
        "general_recommendations": "Reposo vocal. Hidratación con líquidos fríos o tibios. Evaluar si hay absceso periamigdalino. Considerar amigdalectomía si es recurrente (>5 episodios/año).",
    },
    {
        "disease_name": "Rinitis Alérgica",
        "medicines": [
            {"name": "Loratadina 10mg", "dosage": "10mg", "frequency": "Cada 24 horas", "duration": "Según temporada"},
            {"name": "Budesonida nasal", "dosage": "2 atomizaciones", "frequency": "Cada 12 horas", "duration": "Durante exposición"},
        ],
        "general_recommendations": "Identificar y evitar alérgenos. Lavados nasales con solución salina. Considerar inmunoterapia si es severa.",
    },
    {
        "disease_name": "Intoxicación Alimentaria",
        "medicines": [
            {"name": "Solución de rehidratación oral", "dosage": "1L", "frequency": "A demanda", "duration": "Durante cuadro"},
            {"name": "Lactobacillus (probiótico)", "dosage": "1 sobre", "frequency": "Cada 12 horas", "duration": "7 días"},
        ],
        "general_recommendations": "Hidratación abundante. Dieta blanda. Carbón activado solo si fue hace <1 hora. Signos de alarma: fiebre >38.5°C, heces con sangre, signos de deshidratación severa.",
    },
    {
        "disease_name": "Tuberculosis",
        "medicines": [
            {"name": "Rifampicina 600mg", "dosage": "600mg", "frequency": "Cada 24 horas", "duration": "6 meses"},
            {"name": "Isoniacida 300mg", "dosage": "300mg", "frequency": "Cada 24 horas", "duration": "6 meses"},
            {"name": "Pirazinamida 1500mg", "dosage": "1500mg", "frequency": "Cada 24 horas", "duration": "2 meses"},
            {"name": "Etambutol 800mg", "dosage": "800mg", "frequency": "Cada 24 horas", "duration": "2 meses"},
        ],
        "general_recommendations": "TRATAMIENTO SUPERVISADO (DOTS). Notificación obligatoria a salud pública. Aislamiento respiratorio las primeras 2 semanas de tratamiento. Monitoreo de función hepática por hepatotoxicidad de los fármacos.",
    },
    {
        "disease_name": "Shigelosis (Disentería)",
        "medicines": [
            {"name": "Ciprofloxacina 500mg", "dosage": "500mg", "frequency": "Cada 12 horas", "duration": "5 días"},
            {"name": "Solución de rehidratación oral", "dosage": "1-2L", "frequency": "A demanda", "duration": "Durante cuadro"},
            {"name": "Lactobacillus (probiótico)", "dosage": "1 sobre", "frequency": "Cada 12 horas", "duration": "7 días"},
        ],
        "general_recommendations": "Aislamiento entérico. Higiene de manos estricta. No usar loperamida (riesgo de megacolon tóxico). Reporte a salud pública obligatorio.",
    },
    {
        "disease_name": "Infarto Agudo de Miocardio",
        "medicines": [
            {"name": "Ácido acetilsalicílico 300mg", "dosage": "300mg", "frequency": "Dosis única masticado", "duration": "1 dosis"},
            {"name": "Nitroglicerina sublingual 0.5mg", "dosage": "0.5mg", "frequency": "Cada 5 minutos (máx 3 dosis)", "duration": "Durante dolor"},
            {"name": "Clopidogrel 300mg", "dosage": "300mg", "frequency": "Dosis única", "duration": "1 dosis"},
            {"name": "Heparina sódica IV", "dosage": "60 UI/kg", "frequency": "Bolo inicial", "duration": "Durante hospitalización"},
            {"name": "Morfina 2-4mg IV", "dosage": "2-4mg", "frequency": "Cada 5-15 minutos PRN", "duration": "Durante dolor severo"},
        ],
        "general_recommendations": "EMERGENCIA MÉDICA - Activar código infarto. Traslado a unidad de hemodinamia. Monitoreo cardíaco continuo. Reposo absoluto. Oxígeno suplementario. Angioplastía primaria idealmente <90 min.",
    },
    {
        "disease_name": "Insuficiencia Cardíaca",
        "medicines": [
            {"name": "Furosemida 40mg", "dosage": "40mg", "frequency": "Cada 12 horas", "duration": "Crónico"},
            {"name": "Enalapril 10mg", "dosage": "10mg", "frequency": "Cada 12 horas", "duration": "Crónico"},
            {"name": "Carvedilol 6.25mg", "dosage": "6.25mg", "frequency": "Cada 12 horas", "duration": "Crónico"},
            {"name": "Espironolactona 25mg", "dosage": "25mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
        ],
        "general_recommendations": "Restricción de sodio (<2g/día). Control diario de peso. Monitoreo de ingesta y diuresis. Evaluar fracción de eyección. Considerar trasplante cardíaco si refractario.",
    },
    {
        "disease_name": "Hipertensión Arterial",
        "medicines": [
            {"name": "Losartán 50mg", "dosage": "50mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
            {"name": "Hidroclorotiazida 12.5mg", "dosage": "12.5mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
        ],
        "general_recommendations": "Reducción de sodio en la dieta. Ejercicio aeróbico 150 min/semana. Control de peso. Monitoreo de PA en casa. Evaluar daño a órgano blanco (corazón, riñón, cerebro).",
    },
    {
        "disease_name": "Diabetes Mellitus Tipo 2",
        "medicines": [
            {"name": "Metformina 850mg", "dosage": "850mg", "frequency": "Cada 12 horas con comidas", "duration": "Crónico"},
            {"name": "Glibenclamida 5mg", "dosage": "5mg", "frequency": "Cada 24 horas antes del desayuno", "duration": "Crónico"},
        ],
        "general_recommendations": "Plan de alimentación saludable. Ejercicio regular. Automonitoreo de glucosa capilar. Control de HbA1c cada 3 meses. Evaluación anual de fondo de ojo, pie diabético y función renal.",
    },
    {
        "disease_name": "Hipotiroidismo",
        "medicines": [
            {"name": "Levotiroxina sódica 50-100mcg", "dosage": "50-100mcg", "frequency": "Cada 24 horas en ayunas", "duration": "Crónico"},
        ],
        "general_recommendations": "Tomar levotiroxina 30-60 min antes del desayuno. Monitorear TSH cada 6-8 semanas hasta ajuste, luego anual. Evitar calcio y hierro junto con la medicación.",
    },
    {
        "disease_name": "Hipertiroidismo",
        "medicines": [
            {"name": "Metimazol 15-30mg", "dosage": "15-30mg", "frequency": "Cada 24 horas", "duration": "12-18 meses"},
            {"name": "Propranolol 40mg", "dosage": "40mg", "frequency": "Cada 8 horas", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Monitoreo de función tiroidea cada 4-6 semanas. Evaluar remisión después de 12-18 meses. Considerar yodo radiactivo o cirugía si no responde. Evitar cafeína y estimulantes.",
    },
    {
        "disease_name": "Migraña",
        "medicines": [
            {"name": "Ibuprofeno 400mg", "dosage": "400mg", "frequency": "Cada 8 horas", "duration": "Durante crisis"},
            {"name": "Sumatriptán 50mg", "dosage": "50mg", "frequency": "Dosis única al inicio del dolor", "duration": "Durante crisis"},
            {"name": "Metoclopramida 10mg", "dosage": "10mg", "frequency": "Cada 8 horas PRN", "duration": "Durante crisis"},
        ],
        "general_recommendations": "Identificar y evitar desencadenantes. Habitación oscura y silenciosa durante crisis. Considerar profilaxis si >4 crisis/mes con topiramato o propranolol.",
    },
    {
        "disease_name": "Accidente Cerebrovascular (ACV)",
        "medicines": [
            {"name": "Activador de plasminógeno tisular (tPA)", "dosage": "0.9mg/kg IV", "frequency": "Dosis única dentro de 4.5h", "duration": "1 dosis"},
            {"name": "Ácido acetilsalicílico 100mg", "dosage": "100mg", "frequency": "Cada 24 horas (post tPA)", "duration": "Crónico"},
            {"name": "Clopidogrel 75mg", "dosage": "75mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
            {"name": "Atorvastatina 40mg", "dosage": "40mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
        ],
        "general_recommendations": "EMERGENCIA MÉDICA - Activación de código ACV. TC cerebral inmediato. Ventana de trombólisis 4.5 horas. Unidad de ACV. Rehabilitación temprana: fonoaudiología, terapia ocupacional, fisioterapia.",
    },
    {
        "disease_name": "Epilepsia",
        "medicines": [
            {"name": "Ácido valproico 500mg", "dosage": "500mg", "frequency": "Cada 12 horas", "duration": "Crónico"},
            {"name": "Levetiracetam 500mg", "dosage": "500mg", "frequency": "Cada 12 horas", "duration": "Crónico"},
        ],
        "general_recommendations": "Evitar desencadenantes (falta de sueño, alcohol, luces). No suspender medicación abruptamente. Evaluar conducción vehicular según normativa local. EEG y control neurológico periódico.",
    },
    {
        "disease_name": "Enfermedad de Parkinson",
        "medicines": [
            {"name": "Levodopa/Carbidopa 250/25mg", "dosage": "250/25mg", "frequency": "Cada 8 horas", "duration": "Crónico"},
            {"name": "Pramipexol 0.25mg", "dosage": "0.25mg", "frequency": "Cada 8 horas", "duration": "Crónico"},
        ],
        "general_recommendations": "Fisioterapia y terapia ocupacional. Ejercicio regular (tai chi, baile). Evaluar disfagia y riesgo de caídas. Apoyo psicológico. Considerar estimulación cerebral profunda en casos avanzados.",
    },
    {
        "disease_name": "Artritis Reumatoide",
        "medicines": [
            {"name": "Metotrexato 7.5-15mg", "dosage": "7.5-15mg", "frequency": "1 vez por semana", "duration": "Crónico"},
            {"name": "Ácido fólico 5mg", "dosage": "5mg", "frequency": "Cada 24 horas excepto día de metotrexato", "duration": "Crónico"},
            {"name": "Prednisolona 5-10mg", "dosage": "5-10mg", "frequency": "Cada 24 horas", "duration": "Dosis descendente"},
            {"name": "Ibuprofeno 400mg", "dosage": "400mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Reumatología de seguimiento. Fisioterapia para mantener rango articular. Ejercicios de bajo impacto. Evaluar necesidad de terapia biológica si no responde. Monitoreo de efectos adversos del metotrexato.",
    },
    {
        "disease_name": "Lupus Eritematoso Sistémico",
        "medicines": [
            {"name": "Hidroxicloroquina 200mg", "dosage": "200mg", "frequency": "Cada 12 horas", "duration": "Crónico"},
            {"name": "Prednisolona 10-60mg", "dosage": "10-60mg", "frequency": "Cada 24 horas", "duration": "Según actividad"},
            {"name": "Micofenolato mofetilo 1g", "dosage": "1g", "frequency": "Cada 12 horas", "duration": "Crónico"},
        ],
        "general_recommendations": "Protección solar estricta (FPS 50+). Evaluación periódica de función renal. Control de presión arterial. Vacunación antineumocócica y antigripal. Evitar embarazo no planificado (alto riesgo).",
    },
    {
        "disease_name": "Malaria",
        "medicines": [
            {"name": "Artemeter-Lumefantrina 20/120mg", "dosage": "4 comprimidos", "frequency": "Cada 12 horas", "duration": "3 días"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas", "duration": "5 días"},
        ],
        "general_recommendations": "Tratamiento supervisado. Notificación obligatoria. Mosquitero impregnado con insecticida. Evaluar complicaciones: malaria cerebral, insuficiencia renal, edema pulmonar. Seguimiento de parasitemia a las 48h.",
    },
    {
        "disease_name": "Fiebre Tifoidea",
        "medicines": [
            {"name": "Ceftriaxona 2g IV", "dosage": "2g", "frequency": "Cada 24 horas", "duration": "7-10 días"},
            {"name": "Azitromicina 500mg", "dosage": "500mg", "frequency": "Cada 24 horas", "duration": "7 días"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Aislamiento entérico. Notificación obligatoria. Higiene de manos. Evitar alimentos contaminados. Seguimiento de portadores asintomáticos. Vacunación para viajeros.",
    },
    {
        "disease_name": "Varicela",
        "medicines": [
            {"name": "Acetaminofén 500mg", "dosage": "500mg", "frequency": "Cada 6 horas PRN", "duration": "5 días"},
            {"name": "Loción de calamina", "dosage": "Tópica", "frequency": "Cada 6 horas PRN", "duration": "Según necesidad"},
            {"name": "Aciclovir 800mg", "dosage": "800mg", "frequency": "5 veces al día", "duration": "7 días"},
        ],
        "general_recommendations": "NO USAR ASPIRINA por riesgo de síndrome de Reye. Aislamiento hasta que todas las lesiones estén en costra (5-7 días). Baños de avena para prurito. Mantener uñas cortas para evitar infección secundaria. Vacunación para contactos susceptibles.",
    },
    {
        "disease_name": "Herpes Zóster",
        "medicines": [
            {"name": "Aciclovir 800mg", "dosage": "800mg", "frequency": "5 veces al día", "duration": "7-10 días"},
            {"name": "Gabapentina 300mg", "dosage": "300mg", "frequency": "Cada 8 horas", "duration": "Según dolor"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
            {"name": "Lidocaína parche 5%", "dosage": "1 parche", "frequency": "Cada 12 horas", "duration": "Durante dolor agudo"},
        ],
        "general_recommendations": "Tratamiento antiviral temprano reduce riesgo de neuralgia postherpética. Mantener lesiones limpias y secas. Evaluar vacunación (Zostavax/Shingrix) en >50 años. El dolor puede persistir meses después de la erupción.",
    },
    {
        "disease_name": "VIH (Infección Aguda)",
        "medicines": [
            {"name": "Tenofovir disoproxil 300mg", "dosage": "300mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
            {"name": "Emtricitabina 200mg", "dosage": "200mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
            {"name": "Dolutegravir 50mg", "dosage": "50mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
        ],
        "general_recommendations": "Inicio inmediato de TAR. Notificación obligatoria. Prueba de carga viral y CD4 al diagnóstico. Perfil de resistencia. Evaluar coinfecciones (TB, hepatitis). PrEP para parejas. Uso de condón. Seguimiento mensual hasta supresión viral.",
    },
    {
        "disease_name": "Mononucleosis Infecciosa",
        "medicines": [
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "5-7 días"},
            {"name": "Ibuprofeno 400mg", "dosage": "400mg", "frequency": "Cada 8 horas PRN", "duration": "5-7 días"},
        ],
        "general_recommendations": "REPOSO ABSOLUTO. Evitar deportes de contacto por riesgo de ruptura esplénica (por 4-8 semanas). Hidratación abundante. Gárgaras de agua tibia con sal. No usar ampicilina/amoxicilina (causa rash). La fatiga puede persistir semanas.",
    },
    {
        "disease_name": "Leptospirosis",
        "medicines": [
            {"name": "Doxiciclina 100mg", "dosage": "100mg", "frequency": "Cada 12 horas", "duration": "7 días"},
            {"name": "Ceftriaxona 1g IV", "dosage": "1g", "frequency": "Cada 24 horas", "duration": "7 días"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Notificación obligatoria. Hospitalización si hay ictericia o insuficiencia renal. Evitar exposición a aguas contaminadas. Uso de botas y guantes en trabajos de riesgo. Monitoreo de función renal y hepática.",
    },
    {
        "disease_name": "Brucelosis",
        "medicines": [
            {"name": "Doxiciclina 100mg", "dosage": "100mg", "frequency": "Cada 12 horas", "duration": "6 semanas"},
            {"name": "Rifampicina 600mg", "dosage": "600mg", "frequency": "Cada 24 horas", "duration": "6 semanas"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Notificación obligatoria. Evitar consumo de lácteos no pasteurizados. Protección en mataderos y establos. Monitoreo de recaídas (pueden ocurrir hasta 6 meses después). Evaluar complicaciones como espondilitis y endocarditis.",
    },
    {
        "disease_name": "Asma Bronquial",
        "medicines": [
            {"name": "Salbutamol inhalador 100mcg", "dosage": "2 inhalaciones", "frequency": "Cada 4-6 horas PRN", "duration": "Durante crisis"},
            {"name": "Budesonida inhalador 200mcg", "dosage": "2 inhalaciones", "frequency": "Cada 12 horas", "duration": "Crónico"},
            {"name": "Montelukast 10mg", "dosage": "10mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
        ],
        "general_recommendations": "Identificar y evitar desencadenantes (ácaros, polen, humo). Plan de acción escrito. Técnica inhalatoria correcta. Pico-flujo diario. Vacunación antigripal y antineumocócica. Evaluar control cada 3 meses.",
    },
    {
        "disease_name": "EPOC",
        "medicines": [
            {"name": "Salbutamol inhalador 100mcg", "dosage": "2 inhalaciones", "frequency": "Cada 4-6 horas PRN", "duration": "Crónico"},
            {"name": "Tiotropio inhalador 18mcg", "dosage": "1 inhalación", "frequency": "Cada 24 horas", "duration": "Crónico"},
            {"name": "Fluticasona/Salmeterol 250/50mcg", "dosage": "2 inhalaciones", "frequency": "Cada 12 horas", "duration": "Crónico"},
            {"name": "Oxígeno domiciliario", "dosage": "1-2L/min", "frequency": "≥16 horas/día", "duration": "Crónico si PaO2 <55mmHg"},
        ],
        "general_recommendations": "CESAR DE FUMAR es la medida más importante. Vacunación antigripal y antineumocócica anual. Rehabilitación pulmonar. Evaluación de gasometría arterial. Valorar cirugía de reducción de volumen en casos seleccionados.",
    },
    {
        "disease_name": "Laringitis Aguda",
        "medicines": [
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "3-5 días"},
            {"name": "Ibuprofeno 400mg", "dosage": "400mg", "frequency": "Cada 8 horas PRN", "duration": "3-5 días"},
        ],
        "general_recommendations": "REPOSO VOCAL ABSOLUTO (no hablar ni susurrar). Hidratación abundante. Evitar irritantes (tabaco, alcohol). Vaporizaciones con agua tibia. No requiere antibióticos (viral en >90%). Si persiste >2 semanas, evaluar por ORL.",
    },
    {
        "disease_name": "Apendicitis Aguda",
        "medicines": [
            {"name": "Ceftriaxona 1g IV", "dosage": "1g", "frequency": "Cada 12 horas IV", "duration": "Hasta cirugía"},
            {"name": "Metronidazol 500mg IV", "dosage": "500mg", "frequency": "Cada 8 horas IV", "duration": "Hasta cirugía"},
            {"name": "Analgesia (Tramadol 50mg IV)", "dosage": "50mg", "frequency": "Cada 8 horas PRN", "duration": "Hasta cirugía"},
        ],
        "general_recommendations": "URGENCIA QUIRÚRGICA - Apendicectomía laparoscópica o abierta. NADA VÍA ORAL (NPO). Ayuno prequirúrgico. Antibióticos preoperatorios. Si hay perforación, antibióticos por 7-10 días postcirugía.",
    },
    {
        "disease_name": "Colecistitis",
        "medicines": [
            {"name": "Ceftriaxona 1g IV", "dosage": "1g", "frequency": "Cada 12 horas IV", "duration": "Hasta cirugía"},
            {"name": "Metronidazol 500mg IV", "dosage": "500mg", "frequency": "Cada 8 horas IV", "duration": "Hasta cirugía"},
            {"name": "Hioscina 20mg IV", "dosage": "20mg", "frequency": "Cada 8 horas PRN", "duration": "Durante dolor"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "URGENCIA QUIRÚRGICA - Colecistectomía laparoscópica. Dieta baja en grasas. NPO prequirúrgico. Ultrasonido abdominal para confirmar. Evaluar coledocolitiasis con MRCP si hay ictericia o elevación de bilirrubina.",
    },
    {
        "disease_name": "Úlcera Péptica",
        "medicines": [
            {"name": "Omeprazol 20mg", "dosage": "20mg", "frequency": "Cada 12 horas", "duration": "8 semanas"},
            {"name": "Amoxicilina 1g", "dosage": "1g", "frequency": "Cada 12 horas", "duration": "14 días (si H. pylori)"},
            {"name": "Claritromicina 500mg", "dosage": "500mg", "frequency": "Cada 12 horas", "duration": "14 días (si H. pylori)"},
            {"name": "Antiácido (Hidróxido de aluminio)", "dosage": "10ml", "frequency": "Cada 6 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Prueba de H. pylori con antígeno en heces o aliento. Si es positivo: triple terapia 14 días. Evitar AINEs, alcohol y tabaco. Comidas pequeñas y frecuentes. Endoscopia de control si persisten síntomas. Signos de alarma: hematemesis, melena, dolor abdominal severo.",
    },
    {
        "disease_name": "Reflujo Gastroesofágico (ERGE)",
        "medicines": [
            {"name": "Omeprazol 20mg", "dosage": "20mg", "frequency": "Cada 24 horas antes del desayuno", "duration": "8 semanas"},
            {"name": "Antiácido (Almagato)", "dosage": "10ml", "frequency": "Cada 6 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Elevar cabecera de cama 30°. Evitar comidas 3h antes de dormir. Reducir café, té, chocolate, cítricos, fritos. Pérdida de peso si sobrepeso. Evitar ropa apretada. Endoscopia si síntomas de alarma (disfagia, pérdida de peso).",
    },
    {
        "disease_name": "Cólico Nefrítico",
        "medicines": [
            {"name": "Diclofenaco 75mg IM", "dosage": "75mg", "frequency": "Dosis única", "duration": "Durante dolor"},
            {"name": "Hioscina 20mg IV", "dosage": "20mg", "frequency": "Cada 8 horas PRN", "duration": "Durante dolor"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
            {"name": "Tamsulosina 0.4mg", "dosage": "0.4mg", "frequency": "Cada 24 horas", "duration": "Hasta expulsión del cálculo"},
        ],
        "general_recommendations": "Aumentar ingesta de agua (>3L/día). Filtrar la orina para recuperar el cálculo y analizarlo. Analgesia agresiva. Evaluar con TAC de abdomen sin contraste. Si fiebre o dolor intratable: hospitalización. Litotricia o ureteroscopia si cálculo >5mm.",
    },
    {
        "disease_name": "Insuficiencia Renal Aguda",
        "medicines": [
            {"name": "Furosemida 40-80mg IV", "dosage": "40-80mg", "frequency": "Cada 8-12 horas", "duration": "Según respuesta"},
            {"name": "Kayexalato 15g", "dosage": "15g", "frequency": "Cada 6 horas", "duration": "Hasta corregir hiperkalemia"},
            {"name": "Bicarbonato de sodio 1M IV", "dosage": "50-100ml", "frequency": "Dosis única si acidosis severa", "duration": "1 dosis"},
        ],
        "general_recommendations": "HOSPITALIZACIÓN. Identificar causa: prerrenal, renal o postrenal. Suspender nefrotóxicos. Balance hídrico estricto. Dieta baja en potasio y proteínas. Evaluar necesidad de diálisis urgente si hiperkalemia severa, acidosis refractaria o edema pulmonar.",
    },
    {
        "disease_name": "Celulitis",
        "medicines": [
            {"name": "Amoxicilina/Ácido clavulánico 875/125mg", "dosage": "875/125mg", "frequency": "Cada 12 horas", "duration": "7-10 días"},
            {"name": "Clindamicina 300mg", "dosage": "300mg", "frequency": "Cada 8 horas", "duration": "7-10 días"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Inmovilización y elevación del miembro afectado. Marcar borde del eritema con bolígrafo para monitorizar extensión. Hospitalización si: fiebre alta, linfangitis, rápida progresión, inmunosupresión. Evaluar presencia de absceso que requiera drenaje.",
    },
    {
        "disease_name": "Urticaria",
        "medicines": [
            {"name": "Cetirizina 10mg", "dosage": "10mg", "frequency": "Cada 24 horas", "duration": "7-14 días"},
            {"name": "Loratadina 10mg", "dosage": "10mg", "frequency": "Cada 24 horas", "duration": "7-14 días"},
            {"name": "Prednisolona 30mg", "dosage": "30mg", "frequency": "Cada 24 horas por 3 días", "duration": "3 días"},
        ],
        "general_recommendations": "Identificar y evitar desencadenantes (alimentos, medicamentos, infecciones, estrés). Antihistamínicos diarios. Si hay compromiso de vía aérea o angioedema severo: URGENCIA (adrenalina IM). Llevar diario de síntomas.",
    },
    {
        "disease_name": "Dermatitis Atópica",
        "medicines": [
            {"name": "Hidrocortisona crema 1%", "dosage": "Tópico", "frequency": "Cada 12 horas", "duration": "7-14 días"},
            {"name": "Tacrolimus ungüento 0.1%", "dosage": "Tópico", "frequency": "Cada 12 horas", "duration": "Crónico intermitente"},
            {"name": "Cetirizina 10mg", "dosage": "10mg", "frequency": "Cada 24 horas", "duration": "Según prurito"},
            {"name": "Emolientes (crema hidratante)", "dosage": "Tópico", "frequency": "Cada 12 horas y tras baño", "duration": "Crónico"},
        ],
        "general_recommendations": "Baños cortos con agua tibia. Jabón suave sin fragancia. Hidratación abundante de la piel (emolientes). Evitar rascado (mantener uñas cortas). Ropa de algodón. Evitar alérgenos conocidos. Control de infecciones secundarias (Staphylococcus aureus).",
    },
    {
        "disease_name": "Cistitis Intersticial",
        "medicines": [
            {"name": "Amitriptilina 25mg", "dosage": "25mg", "frequency": "Cada 24 horas al acostarse", "duration": "Crónico"},
            {"name": "Pentosano polisulfato 100mg", "dosage": "100mg", "frequency": "Cada 8 horas", "duration": "Crónico"},
            {"name": "Ibuprofeno 400mg", "dosage": "400mg", "frequency": "Cada 8 horas PRN", "duration": "Según síntomas"},
        ],
        "general_recommendations": "Evitar alimentos irritantes (café, té, cítricos, picante, tomate, alcohol). Técnicas de relajación y manejo del estrés. Fisioterapia de suelo pélvico. Micción programada. Evaluar por urología para cistoscopia. Considerar instilaciones vesicales intravesicales.",
    },
    {
        "disease_name": "Fibromialgia",
        "medicines": [
            {"name": "Pregabalina 75mg", "dosage": "75mg", "frequency": "Cada 12 horas", "duration": "Crónico"},
            {"name": "Duloxetina 60mg", "dosage": "60mg", "frequency": "Cada 24 horas", "duration": "Crónico"},
            {"name": "Paracetamol 500mg", "dosage": "500mg", "frequency": "Cada 8 horas PRN", "duration": "Según dolor"},
            {"name": "Tramadol 50mg", "dosage": "50mg", "frequency": "Cada 8 horas PRN", "duration": "Máximo 7 días"},
        ],
        "general_recommendations": "Ejercicio aeróbico de bajo impacto (caminar, natación, tai chi) progresivo. Terapia cognitivo-conductual. Higiene del sueño. Reducción del estrés. Evitar opioides a largo plazo. Grupos de apoyo. El tratamiento es multidisciplinario (reumatología, psiquiatría, fisioterapia).",
    },
]


async def seed():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]

    collections = await db.list_collection_names()
    if "symptoms" in collections:
        await db.symptoms.drop()
        print("Dropped existing symptoms collection")
    if "diseases" in collections:
        await db.diseases.drop()
        print("Dropped existing diseases collection")
    if "treatments" in collections:
        await db.treatments.drop()
        print("Dropped existing treatments collection")

    await db.symptoms.insert_many(symptoms)
    print(f"Inserted {len(symptoms)} symptoms")

    await db.diseases.insert_many(diseases)
    print(f"Inserted {len(diseases)} diseases")

    await db.treatments.insert_many(treatments)
    print(f"Inserted {len(treatments)} treatments")

    client.close()
    print("Seed completed!")


if __name__ == "__main__":
    asyncio.run(seed())
